server {
    listen 80;
    # Nginx accepts HTTP requests on port 80 Remember we mapped: 8000:80 so localhost:8000 → nginx:80
    index index.php index.html;
    server_name localhost;

    client_max_body_size 100M;

    root /var/www/public;
    # this line saying The website files that Nginx should serve are located in /var/www/public. how its get there !! dont forget we map it via the volume in the docker-compose.yml .:/var/www

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass app:9000; 
        # This is the most important line. It means: Send the requests to the container named "app" on port 9000 note we tell the host name (which match the service name we put in the docker.compose.yml) and the port also in the database later in the .env DB_HOST=mysql, this represint the Hostnameand  DB_PORT=3306, which Port number
        # 1️⃣ Hostname (which container to reach)
        # 2️⃣ Port number (which service inside that container)
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    location ~ /\.ht {
        deny all;
    }

    # This prevents access to hidden files like .env.
}